FROM        quay.io/prometheus/busybox-linux-arm64:glibc
MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>

COPY node_exporter_arm64 /bin/node_exporter

EXPOSE      9100
ENTRYPOINT  [ "/bin/node_exporter" ]